### ISSUE TITLE
CI/CD integration to code-gov-style

### ISSUE THREAD

**Issue by BalajiJBcs** [GSA/code-gov-style#25]
There is no CI/CD mechanism (like circleCI/Travis/Jenkins) in place for automated testing before the code deployment to the production environment through a manual testing deployment. It is possible that bugs might be missed, a CI/CD mechanism may be in place in for the code-gov-style, so the developer would test and deploy the code faster.

**Comment by DanielJDufour** [comment]
Hi, @BalajiJBcs .  This is a great suggestion!  Automated testing would be very welcome :-)

We would especially appreciate automated testing with Circle CI because this is what we currently use and have approval to run :-)

**Comment by saracope** [comment]
Added in #53
