### ISSUE TITLE
Increase Width of Data Quality Score Tag

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-style#31]
**Is your feature request related to a problem? Please describe.**
Need width to be larger per https://github.com/GSA/caribou/issues/8

**Describe the solution you'd like**
Edit the scss file for the card https://github.com/GSA/code-gov-style/blob/master/_sass/_cards.scss#L21

**Describe alternatives you've considered**
N/A

**Additional context**
After the update in made the code-gov-style, we'll need to update the version of code-gov-style for the main site.

**Comment by DanielJDufour** [comment]
@BalajiJBcs , for your reference: https://gsa.github.io/code-gov-style/components/corner_tags

**Comment by saracope** [comment]
This was fixed in #45, closing out.
