### ISSUE TITLE
Sidebar should change text to blue on hover

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-style#37]
**Is your feature request related to a problem? Please describe.**
Change styling on hover in sidebar

**Describe the solution you'd like**
Hover should change text to blue and shouldn't change background

**Describe alternatives you've considered**

**Additional context**
https://github.com/GSA/caribou/issues/41

The sidebar styling is used by the about section

**Comment by DanielJDufour** [comment]
Here's current version: https://gsa.github.io/code-gov-style/components/sidebars

**Comment by coreyjjames** [comment]
I can do this
