### ISSUE TITLE
Internet Explorer: Filter Box Text Misplaced

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-style#41]
**Describe the bug**

**To Reproduce**
1. Go to https://gsa.github.io/code-gov-style/components/filter

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/48498056-5e556200-e803-11e8-8cfe-6bf27104d3bb.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] IE

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saracope** [comment]
Thanks for the guidance here @peterbenoit! We are helping with a hackathon on May 18th, so I'm going to leave this available in case any folks want to PR during that event. 🙏

**Comment by rkramer1964** [comment]
Is this bug still open?  I'm not seeing it on Win 10, IE 11.657.18362.0

**Comment by jcastle** [comment]
Thanks @rkramer1964!

I assume it is still relevant. I would need to test to make sure and this is not priority for us right now. If you test and find it is still relevant, please update here. Thanks.

**Comment by jcastle-zz** [comment]
Deprecating the repo as it's no longer used by Code.gov.
