### ISSUE TITLE
Add CSS/SCSS Linting to CircleCI Pipeline

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-style#46]
**Is your feature request related to a problem? Please describe.**
We currently don't make sure our SCSS styling rules follow any standard.  With regards to long-term sustainability and making open source contributions easier, it would be helpful to use linting to make sure our SCSS is intuitive for most people.

**Describe the solution you'd like**
We could find a CSS/SCSS linter and add it as a workflow step in CircleCI's config.yml file

**Describe alternatives you've considered**
Would be awesome if there's already a Github app / webhooks that we can install that would provide this out of the box.

**Additional context**
This inspired my thinking here: https://github.com/MapStory/mapstory/wiki/CSS-Styleguide
(Note: I sometimes volunteer for MapStory and used to work there).

This is another issue on enhancing our CI/CD system: https://github.com/GSA/code-gov-front-end/issues/127

**Comment by saracope** [comment]
I've added the [18f stylelint rules](https://github.com/18F/stylelint-rules) to the project, but it identified almost 600 problems that need reviewed/resolved.  Will look at adding it to circleci when these are resolved.

**Comment by saracope** [comment]
Added in #56
