### ISSUE TITLE
Resolve stylelint problems

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-style#51]
We've added the [18f stylelint rules](https://github.com/18F/stylelint-rules) to this project for testing. A first run has identified almost 600 problems. This is a barrier to adding it to the circleci config since it would just fail every time. 

TODO: Resolve the stylelint errors.

HOW: Run `npm test` on the master branch to generate the error report. Review this and tackle these file updates a few at a time.  It will be easier for me to review pull requests for these changes if they happen in small batches.

Please reply here with any questions!

**Comment by vollmerr** [comment]
Is there a requirement for using the 18f stylelint rules package? I tried adding in just using [stylelint](https://github.com/stylelint/stylelint) directly with the [standard config](https://github.com/stylelint/stylelint-config-standard) (which could be configured) and it seems like that would be better for fixing these issues and user experience. It allows using an extension to see the issues in code, such as using the stylelint extension in vs code:

![image](https://user-images.githubusercontent.com/22438106/55125480-0854cd00-50c7-11e9-8310-ba77af40bfb9.png)

Also, using stylelint I ran it with the --fix option and about half the issues where automatically fixed. Here is with just running the auto fix and standard config: https://github.com/vollmerr/code-gov-style/pull/1 

Probably the biggest difference I see between the standard config I mentioned above and the one currently used is the declaration-no-important rule, that does not allow using !important. If you keep that rule it seems like there is going to have to be a lot of testing to make sure nothing breaks when an important is removed (in 35 places)

**Comment by saracope** [comment]
I'm haven't been able to get an answer to this. The 18f stylelint rules aren't being maintained and I'd rather not use it. I will ping again but if there's no response I don't have a problem with just moving to stylelint.

**Comment by saracope** [comment]
Added a new issue for moving to the stylelint standard config: #55

**Comment by saracope** [comment]
This has been updated to the standard config, but still has some fixes that are needed.

**Comment by vollmerr** [comment]
Have started PR #57 for this. Let me know if you are wanting smaller commits for easier review
