### ISSUE TITLE
Beef up the usage info in README

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-style#70]
The [README](https://github.com/GSA/code-gov-style/blob/master/README.md#usage) section on `Usage` need more info. This are should explain how to use this style guide with another project via npm and standalone.

[USWDS](https://github.com/uswds/uswds#using-the-design-system) has a pretty well fleshed out section like this.

I also like the `Include GOV.UK Frontend in your project`  section of the [Gov.uk design system](https://design-system.service.gov.uk/get-started/production/).

**Comment by jcastle-zz** [comment]
Deprecating the repo as it's no longer used by Code.gov.
