### ISSUE TITLE
Document site code vs. style code

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-style#74]
Clarify that this project is two things: 1. a site to show the style guide 2. code to implement the styles within another project.

Update the documentation to include/clarify how to use the code and also how to stand up the site. We've got a start here, but could there be more info that is helpful?

Indicate that you do not need to run the Jekyll site locally in order to use the styles in a project.
User does need to clone locally in order to contribute to the project.

**Comment by jcastle-zz** [comment]
Deprecating the repo as it's no longer used by Code.gov.
