### ISSUE TITLE
Error on serve

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-style#75]
**Describe the bug**

**To Reproduce**
1. Setup the project locally
2. Execute `npm run serve` from the command line
3. Application starts
4. Error produced `** ERROR: directory is already being watched! **` along with a bunch of follow on errors.

**Expected behavior**

Starting the application should not produce errors.

**Comment by jcastle-zz** [comment]
Deprecating the repo as it's no longer used by Code.gov.
