### ISSUE TITLE
Update `update-custom-elements` script

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-style#76]
For [package.json](https://github.com/GSA/code-gov-style/blob/master/package.json), the `update-custom-elements` script has an extra command that isn't doing anything: ` && npm build`.

There's no build script in the file for it to find and run. 

Action:

Remove ` && npm build` so that the script is only
`"update-custom-elements": "npm install -S @webcomponents/custom-elements && cd node_modules/@webcomponents/custom-elements && npm install"`

**Comment by mflash123** [comment]
Didnt understand your questin but command `&&` means execute if command before was success.
For example `command_1 && command_2` Means: execute command 2 if command 1 results without error..
So, maybe in your case `&& npm build` isnt doing anything because previous command wasnt success

**Comment by saracope** [comment]
-> There's no build script in the file for it to find and run. @mflash123
